WORD_LIST = [
    {"word": "cat", "sentence": "the cat sat on the mat"},
    {"word": "dog", "sentence": "the dog barked at the stranger"},
    {"word": "hat", "sentence": "she wore a red hat to the party"},
    {"word": "apple", "sentence": "an apple a day keeps the doctor away"},
    {"word": "table", "sentence": "we sat around the table for dinner"},
    {"word": "light", "sentence": "the light from the window filled the room"},
    {"word": "bridge", "sentence": "we crossed the bridge over the river"},
    {"word": "knight", "sentence": "the knight in shining armor rescued the princess"},
    {"word": "phrase", "sentence": "she used a clever phrase to end her speech"},
    {"word": "colonel", "sentence": "the colonel led his troops into battle"},
    {"word": "rhythm", "sentence": "the drummer kept a steady rhythm throughout the song"},
    {"word": "gauge", "sentence": "the fuel gauge showed the tank was nearly empty"},
    {"word": "necessary", "sentence": "it is necessary to study for the exam"},
    {"word": "occurrence", "sentence": "this kind of mistake is a rare occurrence"},
    {"word": "lieutenant", "sentence": "the lieutenant reported to the commanding officer"},
    {"word": "pneumonia", "sentence": "she recovered from pneumonia after two weeks in hospital"},
    {"word": "bureaucracy", "sentence": "the bureaucracy made it difficult to get anything done"},
    {"word": "conscientious", "sentence": "she was a conscientious student who never missed a deadline"},
    {"word": "acquiesce", "sentence": "he chose to acquiesce rather than argue further"},
    {"word": "ephemeral", "sentence": "the beauty of cherry blossoms is ephemeral"},
    {"word": "idiosyncrasy", "sentence": "his habit of humming while working was an endearing idiosyncrasy"},
    {"word": "mnemonic", "sentence": "she used a mnemonic device to remember the order of the planets"},
    {"word": "phlegmatic", "sentence": "he remained phlegmatic even when everyone else was panicking"},
    {"word": "sacrilegious", "sentence": "it would be sacrilegious to desecrate such a sacred place"},
    {"word": "supersede", "sentence": "the new policy will supersede all previous guidelines"},
]

WORDS_PER_GAME = 10
